### ISSUE TITLE
Import matrix_client.errors

### ISSUE THREAD

**Issue by ralfi** [saadnpq/matrixcli#3]
Hi,

if i try to use matrixcli the import of matrix_client errors can not be do. How to fix this or where are these located?

Regards!

**Comment by ralfi** [comment]
Of course i do pip install matrix_client

**Comment by saadnpq** [comment]
i am not using the upstream matrix_client repo i am using my fork as a submodule. did you follow the installation guide in the readme ?

**Comment by saadjsct** [comment]
please see if the new installation method solves it , and thank you for opening the issue.

**Comment by ralfi** [comment]
No prob, will try it asap. Thanks for your code and response.
