### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by Xohwie1i** [saadnpq/matrixcli#4]
Hello, I believe there might be a parsing error. I get a 404 error using "https://matrix.org/" in my config.py file, while using "https://matrix.org" works just fine.

**Comment by saadjsct** [comment]
this problem actually is in the matrix python sdk, what i can do now is to mention this in the README as i am planning to migrate this project to matrix nio soon. thank you for opening the issue.

**Comment by Xohwie1i** [comment]
Awesome, thanks for the quick reply. And, by the way, this is a really great piece of software...thanks for your effort.
